# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7142c49661ed080f7b0b1bdf02d4efba82b86c04bafe878ce11c8ad894485f8f71909ba188a8b58526c1e124326cfb8a98619471fc1fa24f60f6d8c36b568407

test:
  secret_key_base: f948e024740ee5ca45bcb63a9884e1557b2753c81a1df81f0dc42a5bbe4e8218793fb13baad766ef406b691d4815a87b37957dd8bce5c288d8453079136ac26e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
